// OTOMATİK ÜRETİLDİ — elle düzenlemeyin. content/art içeriğinden türetilir.

export const artworkAssets: Record<string, number> = {
  'ani-stres-molasi': require('../../content/art/ani-stres-molasi.jpg'),
  'baslangic-gun-1': require('../../content/art/baslangic-gun-1.jpg'),
  'baslangic-gun-2': require('../../content/art/baslangic-gun-2.jpg'),
  'baslangic-gun-3': require('../../content/art/baslangic-gun-3.jpg'),
  'baslangic-gun-4': require('../../content/art/baslangic-gun-4.jpg'),
  'baslangic-gun-5': require('../../content/art/baslangic-gun-5.jpg'),
  'baslangic-gun-6': require('../../content/art/baslangic-gun-6.jpg'),
  'baslangic-gun-7': require('../../content/art/baslangic-gun-7.jpg'),
  'cat-beden-taramasi': require('../../content/art/cat-beden-taramasi.jpg'),
  'cat-nefes': require('../../content/art/cat-nefes.jpg'),
  'cat-odak': require('../../content/art/cat-odak.jpg'),
  'cat-oz-sefkat': require('../../content/art/cat-oz-sefkat.jpg'),
  'cat-sabah': require('../../content/art/cat-sabah.jpg'),
  'cat-stres-kaygi': require('../../content/art/cat-stres-kaygi.jpg'),
  'cat-sukran': require('../../content/art/cat-sukran.jpg'),
  'cat-uyku': require('../../content/art/cat-uyku.jpg'),
  'derin-uyku-yolculugu': require('../../content/art/derin-uyku-yolculugu.jpg'),
  'dort-yedi-sekiz': require('../../content/art/dort-yedi-sekiz.jpg'),
  'eski-sahil-kasabasi': require('../../content/art/eski-sahil-kasabasi.jpg'),
  'gece-dusunceleri-birakma': require('../../content/art/gece-dusunceleri-birakma.jpg'),
  'gune-niyetle-basla': require('../../content/art/gune-niyetle-basla.jpg'),
  'hizli-beden-taramasi': require('../../content/art/hizli-beden-taramasi.jpg'),
  'ic-elestirmenle-baris': require('../../content/art/ic-elestirmenle-baris.jpg'),
  'ise-baslama-odagi': require('../../content/art/ise-baslama-odagi.jpg'),
  'kaygiyi-gozlemle': require('../../content/art/kaygiyi-gozlemle.jpg'),
  'kendine-nazik-ol': require('../../content/art/kendine-nazik-ol.jpg'),
  'kutu-nefesi': require('../../content/art/kutu-nefesi.jpg'),
  'omuzlardaki-yuk': require('../../content/art/omuzlardaki-yuk.jpg'),
  'sabah-enerjisi': require('../../content/art/sabah-enerjisi.jpg'),
  'sakinlesme-nefesi': require('../../content/art/sakinlesme-nefesi.jpg'),
  'sukran-gunlugu': require('../../content/art/sukran-gunlugu.jpg'),
  'tek-nokta-odak': require('../../content/art/tek-nokta-odak.jpg'),
  'tepeden-tirnaga': require('../../content/art/tepeden-tirnaga.jpg'),
  'uc-guzel-sey': require('../../content/art/uc-guzel-sey.jpg'),
  'uykuya-yumusak-gecis': require('../../content/art/uykuya-yumusak-gecis.jpg'),
  'yagmurlu-orman-evi': require('../../content/art/yagmurlu-orman-evi.jpg'),
  'zihinsel-netlik': require('../../content/art/zihinsel-netlik.jpg'),
};
