// OTOMATİK ÜRETİLDİ — elle düzenlemeyin. Yeniden üretmek için: node scripts/gen-artwork.mjs

export const artworkAssets: Record<string, number> = {
  'baslangic-gun-1': require('../../content/art/baslangic-gun-1.png'),
  'baslangic-gun-2': require('../../content/art/baslangic-gun-2.png'),
  'baslangic-gun-3': require('../../content/art/baslangic-gun-3.png'),
  'baslangic-gun-4': require('../../content/art/baslangic-gun-4.png'),
  'baslangic-gun-5': require('../../content/art/baslangic-gun-5.png'),
  'baslangic-gun-6': require('../../content/art/baslangic-gun-6.png'),
  'baslangic-gun-7': require('../../content/art/baslangic-gun-7.png'),
  'uykuya-yumusak-gecis': require('../../content/art/uykuya-yumusak-gecis.png'),
  'gece-dusunceleri-birakma': require('../../content/art/gece-dusunceleri-birakma.png'),
  'derin-uyku-yolculugu': require('../../content/art/derin-uyku-yolculugu.png'),
  'ani-stres-molasi': require('../../content/art/ani-stres-molasi.png'),
  'kaygiyi-gozlemle': require('../../content/art/kaygiyi-gozlemle.png'),
  'omuzlardaki-yuk': require('../../content/art/omuzlardaki-yuk.png'),
  'ise-baslama-odagi': require('../../content/art/ise-baslama-odagi.png'),
  'tek-nokta-odak': require('../../content/art/tek-nokta-odak.png'),
  'zihinsel-netlik': require('../../content/art/zihinsel-netlik.png'),
  'gune-niyetle-basla': require('../../content/art/gune-niyetle-basla.png'),
  'sabah-enerjisi': require('../../content/art/sabah-enerjisi.png'),
  'hizli-beden-taramasi': require('../../content/art/hizli-beden-taramasi.png'),
  'tepeden-tirnaga': require('../../content/art/tepeden-tirnaga.png'),
  'uc-guzel-sey': require('../../content/art/uc-guzel-sey.png'),
  'sukran-gunlugu': require('../../content/art/sukran-gunlugu.png'),
  'kendine-nazik-ol': require('../../content/art/kendine-nazik-ol.png'),
  'ic-elestirmenle-baris': require('../../content/art/ic-elestirmenle-baris.png'),
  'eski-sahil-kasabasi': require('../../content/art/eski-sahil-kasabasi.png'),
  'yagmurlu-orman-evi': require('../../content/art/yagmurlu-orman-evi.png'),
};
