// OTOMATİK ÜRETİLDİ — elle düzenlemeyin. Yeniden üretmek için: npm run content:map

export const audioAssets: Record<string, number> = {
  'baslangic-gun-1': require('../../content/audio/baslangic-gun-1.wav'),
  'baslangic-gun-2': require('../../content/audio/baslangic-gun-2.wav'),
  'baslangic-gun-3': require('../../content/audio/baslangic-gun-3.wav'),
  'baslangic-gun-4': require('../../content/audio/baslangic-gun-4.wav'),
  'baslangic-gun-5': require('../../content/audio/baslangic-gun-5.wav'),
  'baslangic-gun-6': require('../../content/audio/baslangic-gun-6.wav'),
  'baslangic-gun-7': require('../../content/audio/baslangic-gun-7.wav'),
  'uykuya-yumusak-gecis': require('../../content/audio/uykuya-yumusak-gecis.wav'),
  'gece-dusunceleri-birakma': require('../../content/audio/gece-dusunceleri-birakma.wav'),
  'derin-uyku-yolculugu': require('../../content/audio/derin-uyku-yolculugu.wav'),
  'ani-stres-molasi': require('../../content/audio/ani-stres-molasi.wav'),
  'kaygiyi-gozlemle': require('../../content/audio/kaygiyi-gozlemle.wav'),
  'omuzlardaki-yuk': require('../../content/audio/omuzlardaki-yuk.wav'),
  'ise-baslama-odagi': require('../../content/audio/ise-baslama-odagi.wav'),
  'tek-nokta-odak': require('../../content/audio/tek-nokta-odak.wav'),
  'zihinsel-netlik': require('../../content/audio/zihinsel-netlik.wav'),
  'gune-niyetle-basla': require('../../content/audio/gune-niyetle-basla.wav'),
  'sabah-enerjisi': require('../../content/audio/sabah-enerjisi.wav'),
  'hizli-beden-taramasi': require('../../content/audio/hizli-beden-taramasi.wav'),
  'tepeden-tirnaga': require('../../content/audio/tepeden-tirnaga.wav'),
  'uc-guzel-sey': require('../../content/audio/uc-guzel-sey.wav'),
  'sukran-gunlugu': require('../../content/audio/sukran-gunlugu.wav'),
  'kendine-nazik-ol': require('../../content/audio/kendine-nazik-ol.wav'),
  'ic-elestirmenle-baris': require('../../content/audio/ic-elestirmenle-baris.wav'),
  'eski-sahil-kasabasi': require('../../content/audio/eski-sahil-kasabasi.wav'),
  'yagmurlu-orman-evi': require('../../content/audio/yagmurlu-orman-evi.wav'),
  'amb-yagmur': require('../../content/audio/amb-yagmur.wav'),
  'amb-orman-sabahi': require('../../content/audio/amb-orman-sabahi.wav'),
  'amb-deniz-dalgalari': require('../../content/audio/amb-deniz-dalgalari.wav'),
  'amb-beyaz-gurultu': require('../../content/audio/amb-beyaz-gurultu.wav'),
  'amb-gece-circirlari': require('../../content/audio/amb-gece-circirlari.wav'),
};
